DATA:
    ROOT: '/data/UCF101'
    TRAIN_FILE: 'datasets_splits/ucf_splits/train1_few_shot_4.txt'
    VAL_FILE: 'datasets_splits/ucf_splits/val1.txt'
    DATASET: ucf101
    NUM_FRAMES: 32
    NUM_CLASSES: 101
    LABEL_LIST: 'labels/ucf_101_labels.csv'
    LLM_JSON: './LLM_prompts/UCF101/ucf_101_llm_labels.json' 
    
MODEL:
    ARCH: ViT-B/16
    DIM: 512

TRAIN:
    IS_PRETRAIN: False
    BATCH_SIZE: 4 # BS 64
    ACCUMULATION_STEPS: 8
    EPOCHS: 60
    LR: 2e-06
    LR_HEAD: 4e-04
    LR_ADAPTER: 4e-04
    DROPOUT_RATE: 0.0
    REDUCE_DIM: 192
    VAL: False
    WARMUP_EPOCHS: 5

TEST:
    TYPE: "FEWSHOT_VAL"
    COEF_BB: 0.30
    COEF_VIS: 0.10
    COEF_VL: 0.60
    SCALE: 5.0

SAVE_FREQ: 10