DATA:
    ROOT: '/data/hmdb51'
    TRAIN_FILE: 'datasets_splits/base2novel_splits/hmdb_splits/fs_base_s1_train.txt'
    VAL_FILE: 'datasets_splits/base2novel_splits/hmdb_splits/novel_val.txt'
    DATASET: hmdb51
    NUM_FRAMES: 32
    NUM_CLASSES: 25
    LABEL_LIST: 'labels/hmdb_51_novel_labels.csv'
    LLM_JSON: './LLM_prompts/hmdb_51_llm_labels.json'

MODEL:
    ARCH: ViT-B/16
    DIM: 512
    
TRAIN:
    IS_PRETRAIN: True
    BATCH_SIZE: 4 # BS 64
    ACCUMULATION_STEPS: 8
    EPOCHS: 11
    LR: 2e-06
    LR_HEAD: 4e-04
    LR_ADAPTER: 4e-04
    DROPOUT_RATE: 0.0
    REDUCE_DIM: 192
    VAL: False
    WARMUP_EPOCHS: 2

TEST:
    TYPE: "ZEROSHOT_VAL"
    COEF_BB: 0.40
    COEF_VIS: 0.00
    COEF_VL: 0.60
    SCALE: 5.0

SAVE_FREQ: 10  


