DATA:
    ROOT: '/data/hmdb51'
    TRAIN_FILE: 'datasets_splits/hmdb_splits/train1_few_shot_8.txt'
    VAL_FILE: 'datasets_splits/hmdb_splits/val1.txt'
    DATASET: hmdb51
    NUM_FRAMES: 32
    NUM_CLASSES: 51
    LABEL_LIST: 'labels/hmdb_51_labels.csv'
    LLM_JSON: './LLM_prompts/hmdb_51_llm_labels.json'

MODEL:
    ARCH: ViT-B/16
    DIM: 512
    
TRAIN:
    IS_PRETRAIN: False
    BATCH_SIZE: 4 # BS 64
    ACCUMULATION_STEPS: 8
    EPOCHS: 60
    LR: 8e-07
    LR_HEAD: 8e-05
    LR_ADAPTER: 8e-05
    DROPOUT_RATE: 0.8
    REDUCE_DIM: 192
    VAL: False
    WARMUP_EPOCHS: 5

TEST:
    TYPE: "FEWSHOT_VAL"
    COEF_BB: 0.25
    COEF_VIS: 0.20
    COEF_VL: 0.55
    SCALE: 5.0

SAVE_FREQ: 10