DATA:
    ROOT: '/data/SSv2'
    TRAIN_FILE: 'datasets_splits/ssv2_splits/train1_few_shot_8.txt'
    VAL_FILE: 'datasets_splits/ssv2_splits/validation.txt'
    DATASET: ssv2
    NUM_FRAMES: 32
    NUM_CLASSES: 174
    LABEL_LIST: 'labels/ssv2_labels.csv'
    LLM_JSON: './SSv2.json'

MODEL:
    ARCH: ViT-B/16
    DIM: 512
    
TRAIN:
    IS_PRETRAIN: False
    BATCH_SIZE: 4 # BS 64
    ACCUMULATION_STEPS: 8
    EPOCHS: 60
    LR: 1e-06
    LR_HEAD: 2e-04
    LR_ADAPTER: 2e-04
    DROPOUT_RATE: 0.8
    REDUCE_DIM: 192
    WARMUP_EPOCHS: 5
    VAL: False

TEST:
    TYPE: "FEWSHOT_VAL"
    COEF_BB: 0.5
    COEF_VIS: 0.3
    COEF_VL: 0.2
    SCALE: 5.0

SAVE_FREQ: 10  #65.2