DATA:
    ROOT: '/data/k600_extract'
    TRAIN_FILE: 'datasets_splits/k600_splits/ZS_split3_K600_eval.txt'
    VAL_FILE: 'datasets_splits/k600_splits/ZS_split3_K600_eval.txt'
    DATASET: kinetics400
    NUM_FRAMES: 32
    NUM_CLASSES: 160
    LABEL_LIST: 'labels/ZS_split3_K600.csv'
    LLM_JSON: './LLM_prompts/K600/K600_prompts_with_prefix.json'

MODEL:
    ARCH: ViT-B/16
    DIM: 512

TRAIN:
    IS_PRETRAIN: False
    BATCH_SIZE: 4 
    ACCUMULATION_STEPS: 2
    EPOCHS: 50
    LR: 2.e-04
    REDUCE_DIM: 192
    VAL: False

TEST:
    TYPE: "ZEROSHOT_VAL"
    WISE_FT: 0.0
    COEF_BB: 0.9
    COEF_VIS: 0.0
    COEF_VL: 0.1
    
SAVE_FREQ: 10